# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
age = "1.2.1"
bat = "0.25.0"
bottom = "0.11.2"
fd = "10.3.0"
gh = "2.81.0"
"github:cilium/cilium-cli" = "0.18.7"
gitleaks = "8.28.0"
go = "latest"
gradle = "8.14.0"
helm = "latest"
jq = "1.8.1"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
lefthook = "2.0.1"
"aqua:neovim/neovim" = "latest"
node = "22"
postgres = "17"
opentofu = "1.10.6"
python = "3.12"
ripgrep = "14.1.1"
rust = "latest"
talosctl = "1.11.3"
yq = "4.48.1"
1password = "2.35.0-beta.01"

# required by lazyvim
lua = "5.4.8" # MUST be 5.1
lazygit = "0.55.1"
"github:luarocks/luarocks" = "3.12.2"
usage = "latest"
rg = "latest"
acli = "latest"
"github:dloss/kelora" = "latest"
"npm:@anthropic-ai/claude-code" = "2.0.27"
neovim = "latest"
maven = "latest"
java = "20"
pnpm = "11.7.0"
hunk = "latest"
herdr = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
